### ISSUE TITLE
An error at

### ISSUE THREAD

**Issue by anaresh7777** [Hironate/PeerChat#11]
hello sir,
I need some help. I am getting errors when i am running Peerchat Master projects. Here are the errors.
1. "RTCPeerConnection.CreateAnswer without a failure callback is deprecated. The failure callback will be a required parameter in M50. See https://www.chromestatus.com/feature/5663288008376320 for more details"
2. "XMLHttpRequest cannot load https://computeengineondemand.appspot.com/turn?username=41784574&key=4080218913. No access resource.Origin 'https://192.168.178.20:3000' is therefore not allowed access".
Please tell me some suggestions to solve these problems.
Thanks

**Comment by Hironate** [comment]
Hi there,

First of all sorry because I am no longer working on this project. So u will.have to do it ur self. :(

**Comment by anaresh7777** [comment]
Or can you suggest me any references for video chat??

**Comment by Hironate** [comment]
Try keyword webrtc video chat

**Comment by anaresh7777** [comment]
hello Hironate,
can you help me regarding audio?.Audio is not working on my system and
video is working

Thanks & Regards
Naresh

**Comment by Hironate** [comment]
I had worked on this project almost 1.5 year ago. I don't have single idea, what i have done. I would have to complete go through this project. and i m no longer working on this project. sry dude. :(
