### ISSUE TITLE
Cross Network Issue

### ISSUE THREAD

**Issue by Hironate** [Hironate/PeerChat#6]
Some day ago i received a mail, that PeerChat is not working, when it is connected through two different networks. If someone able to solve the issue, it would be really appreciated. 

Thanks

**Comment by bjelm** [comment]
Yes, have the same issue, works fine on a local network. Its, weird because the data communication works fine. Sending messages and so. The video initializes but its just black on remote side.
Too bad, I finally found a simple and good example of webrtc for doing remote video.

**Comment by bjelm** [comment]
And its the same on the demo page http://peerchat.net/
