### ISSUE TITLE
Javascript Injection

### ISSUE THREAD

**Issue by deandunbar** [Hironate/PeerChat#7]
When chatting on the demo it is possible to send a javascript tag to other users and the javascript will execute on the other users' machines. I know the chat app was done as an example but a note about using sanitation might help some users who might just install the app as is. 

Btw awesome project !!!!

**Comment by Hironate** [comment]
Thanks, There are many possibilities what you can do with js.  by the way i m no longer working on this app. So i won't be able to help you.
